# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

variogramLineSimple <- function(vgmModel, dist, bCov = FALSE) {
    .Call(`_atakrig_variogramLineSimple`, vgmModel, dist, bCov)
}

spDistsNN <- function(x1, y1, x2, y2, longlat = FALSE) {
    .Call(`_atakrig_spDistsNN`, x1, y1, x2, y2, longlat)
}

outerProd <- function(v1, v2) {
    .Call(`_atakrig_outerProd`, v1, v2)
}

svAreaCloudByPointVgmInit <- function(discretePoints, areaDistByCentroid, longlat = FALSE) {
    invisible(.Call(`_atakrig_svAreaCloudByPointVgmInit`, discretePoints, areaDistByCentroid, longlat))
}

svAreaCloudByPointVgmEnd <- function() {
    invisible(.Call(`_atakrig_svAreaCloudByPointVgmEnd`))
}

ataSetNumberOfThreadsForOMP <- function(num) {
    invisible(.Call(`_atakrig_ataSetNumberOfThreadsForOMP`, num))
}

svAreaCloudByPointVgm <- function(ptVgmModel) {
    .Call(`_atakrig_svAreaCloudByPointVgm`, ptVgmModel)
}

crossSvAreaCloudByPointVgmInit <- function(discretePointsX, discretePointsY, ptVgmModelX, ptVgmModelY, areaDistByCentroidXY, areaDistByPtsX, areaDistByPtsY, areaDistByPtsXY, areaWeightByPtsX, areaWeightByPtsY, areaWeightByPtsXY) {
    invisible(.Call(`_atakrig_crossSvAreaCloudByPointVgmInit`, discretePointsX, discretePointsY, ptVgmModelX, ptVgmModelY, areaDistByCentroidXY, areaDistByPtsX, areaDistByPtsY, areaDistByPtsXY, areaWeightByPtsX, areaWeightByPtsY, areaWeightByPtsXY))
}

crossSvAreaCloudByPointVgm <- function(xyPointCrossVgm) {
    .Call(`_atakrig_crossSvAreaCloudByPointVgm`, xyPointCrossVgm)
}

crossSvAreaCloudByPointVgmEnd <- function() {
    invisible(.Call(`_atakrig_crossSvAreaCloudByPointVgmEnd`))
}

